import 'package:firebase_core/firebase_core.dart';

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // Replace these values with the Firebase configuration generated by:
    // flutterfire configure
    throw UnsupportedError(
      'Firebase is not configured. Run: flutterfire configure',
    );
  }
}
